---
title: "Boostrap"
output: github_document
---

```{r, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continous.colour = "viridis",
  ggplot2.continous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrere = scale_fill_viridis_d

```


```{r}
library(tidyverse)
library(modelr)
library(p8105.datasets)
set.seed(1)
```

do some boostrapping

make up some data
```{r}
n_samp = 250

sim_df_constant = 
  tibble(
    x = rnorm(n_samp, 1,1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3*x + error
  )

sim_df_nonconstant = 
  sim_df_constant |>
  mutate(
    error = error * .75 * x,
    y = 2 + 3*x + error
  )
```

look at these.
```{r}
sim_df_constant |>
  ggplot(aes(x = x, y = y))+
  geom_point()+
  stat_smooth(method = "lm")
  
```


look ar regression
```{r}
sim_df_constant |>
  lm(y ~ x, data = _) |>
  broom::tidy()|>
  knitr::kable(digits = 3)
```


## draw a boostrap sample.
```{r}
boot_sample = function(df) {
  
  boot_df = 
    sample_frac(df, replace = TRUE) |>
    arrange(x)
  
  return(boot_df)
}
```

running this 
```{r}
sim_df_nonconstant|>
  boot_sample()|>
  ggplot(aes(x = x, y = y))+
  geom_point(alpha = .5)+
  stat_smooth(method = "lm")
```

can we do this as part of an analysis?
```{r}
sim_df_nonconstant|>
  lm(y ~ x, data = _) |>
  broom::tidy()|>
  knitr::kable(digits = 3)
```


## boostrap
```{r}
boot_straps = 
  tibble(
    strap_number = 1:1000,
  )|>
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = sim_df_nonconstant)),
    models = map(strap_sample, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)
  )

bootstrap_results = 
  boot_straps |>
  select(strap_number, results)|>
  unnest(results)|>
  group_by(term)|>
  summarise(
    boot_se = sd(estimate)
  )|>
  knitr::kable(digits = 3)
```

## do this all using modelr
```{r}
boot_straps = 
  sim_df_nonconstant|>
  modelr::bootstrap(1000)|>
  mutate(
    strap = map(strap, as_tibble),
    models = map(strap, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)
  )|>
  select(.id, results)|>
  unnest(results)
```

## what do you want to report
```{r}
boot_straps |>
  group_by(term) |>
  summarise(
    boot_est = mean(estimate),
    boot_se = sd(estimate),
    boot_ci_ll = quantile(estimate, .025),
    boot_ci_ul = quantile(estimate, .975)
  )
```


## airbnb
```{r}
data("nyc_airbnb")

manhattan_df = 
nyc_airbnb |>
  mutate(stars = review_scores_location/2)|>
  rename(borough = neighbourhood_group, neighborhood = neighbourhood) |>
  filter(borough == "Manhattan")|>
  select(price, stars, room_type)|>
  drop_na()
```

plot the data
```{r}
manhattan_df |>
  ggplot(aes(x = stars, y = price))+
  geom_point()+
  stat_smooth(method = "lm", se = FALSE)
```

fit a regression
```{r}
manhattan_df|>
  lm(price ~ stars + room_type, data = _)|>
  broom::tidy()|>
  knitr::kable(digits = 3)
```


bootstrap for better (?) inference.
```{r}
boot_results = 
manhattan_df |>
  modelr::bootstrap(1000)|>
  mutate(
    strap = map(strap, as_tibble),
    models = map(strap, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(models, broom::tidy)
  )|>
  select(.id, results)|>
  unnest(results)

boot_results|>
  filter(term == "stars")|>
  ggplot(aes(estimate))+
  geom_density()

boot_results|>
  group_by(term) |>
  summarise(
    boot_est = mean(estimate),
    boot_se = sd(estimate),
    boot_ci_ll = quantile(estimate, .025),
    boot_ci_ul = quantile(estimate, .975)
  )
  
```


```{r}

```

