---
title: "Cross Validation"
output: github_document
---

```{r, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continous.colour = "viridis",
  ggplot2.continous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrere = scale_fill_viridis_d

```


```{r}
library(tidyverse)
library(modelr)
library(mgcv)
library(SemiPar)

set.seed(1)
```

look at LIDAR data
```{r}
data("lidar")

lidar_df = 
  lidar |>
  as_tibble()|>
  mutate(id = row_number())
  
```


```{r}
lidar_df|>
  ggplot(aes(x= range,y = logratio))+
  geom_point()
```


## try to do CV
3 models, one linear, one smooth, one wiggly

construct training testing df
```{r}
train_df = 
  sample_frac(lidar_df, size = .8)
test_df = anti_join(lidar_df, train_df, by = "id")
```

```{r}
ggplot(train_df, aes(x = range, y = logratio))+
  geom_point()+
  geom_point(data = test_df, color = "lightgreen")
```

fit three models
```{r}
linear_mod = lm(logratio ~ range, data = train_df)
smooth_mod = gam(logratio ~ s(range), data = train_df)
wiggly_mod = gam(logratio ~ s(range, k = 30), sp= 10e-6, data = train_df)

```

look at fits
```{r}
train_df |>
  add_predictions(linear_mod)|>
  ggplot(aes(x = range, y = logratio))+
  geom_point()+
  geom_point(data = test_df, color = "lightblue")+
  geom_line(aes(y = pred, color = "pink"))
```


```{r}
train_df |>
  add_predictions(wiggly_mod)|>
  ggplot(aes(x = range, y = logratio))+
  geom_point()+
  #geom_point(data = test_df, color = "lightblue")+
  geom_line(aes(y = pred, color = "pink"))
```


```{r}
train_df |>
  add_predictions(smooth_mod)|>
  ggplot(aes(x = range, y = logratio))+
  geom_point()+
  geom_point(data = test_df, color = "lightblue")+
  geom_line(aes(y = pred, color = "pink"))
```

compare these numerically using RMSE.
```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## repeat the trian/test split
```{r}
cv_df = 
  crossv_mc(lidar_df, 100)|>
  mutate(
    train = map(train, as_tibble),
    test= map(test, as_tibble)
  )
```


```{r, eval=FALSE}
cv_df |>
  pull(train) |>
  nth(3)|>
  as_tibble()
```


Fit models, extract RMSEs
```{r}
cv_res_df = 
  cv_df |>
  mutate(
    linear_mod = map(train, \(x) lm(logratio ~ range, data = x)),
    smooth_mod = map(train, \(x) gam(logratio ~ s(range), data = x)),
    wiggly_mod = map(train, \(x) gam(logratio ~ s(range, k = 30), sp = 10e-6, data = x))
  )|>
  mutate(
    rmse_linear = map2_dbl(linear_mod, test,rmse),
    rmse_smooth = map2_dbl(smooth_mod, test,rmse),
    rmse_wiggly = map2_dbl(wiggly_mod, test,rmse)
  )
```

look at RMSE distribution
```{r}
cv_res_df |>
  select(starts_with("rmse"))|>
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  )|>
  ggplot(aes(x = model, y = rmse))+
  geom_violin()
```



```{r}
child_df = read_csv("./data/nepalese_children.csv")|>
  mutate(
    weight_ch7 = (weight > 7)*(weight - 7)
  )
```


look at data
```{r}
child_df |>
  ggplot(aes(x = weight, y = armc))+
  geom_point(alpha = .5)
```

fit some models
```{r}
linear_mod1 = lm(armc ~ weight, data = child_df)
pwl_mod = lm(armc ~ weight + weight_ch7, data = child_df)
smooth_mod1 = gam(armc ~ s(weight), data = child_df)
```


```{r}
child_df |>
  add_predictions(linear_mod1)|>
  ggplot(aes(x = weight, y = armc))+
  geom_point(alpha = .5)+
  geom_line(aes(y = pred), color = "lightblue")
```

```{r}
child_df |>
  add_predictions(pwl_mod)|>
  ggplot(aes(x = weight, y = armc))+
  geom_point(alpha = .5)+
  geom_line(aes(y = pred), color = "lightblue")
```


CV to select models
```{r}
cv_df = 
  crossv_mc(child_df, 100)|>
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

apply models and extract RMSE
```{r}
cv_res_df = 
  cv_df |>
  mutate(
    linear_mod1 = map(train, \(x) lm(armc ~ weight, data = x)),
    pwl_mod     = map(train, \(x) lm(armc ~ weight + weight_ch7, data = x)),
    smooth_mod1 = map(train, \(x) gam(armc ~ s(weight), data = x))
  )|>
  mutate(
    rmse_linear = map2_dbl(linear_mod1, test, rmse),
    rmse_pwl    = map2_dbl(pwl_mod, test, rmse),
    rmse_smooth = map2_dbl(smooth_mod1, test, rmse)
  )
```

```{r}
cv_res_df |>
  select(starts_with("rmse"))|>
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  )|>
  ggplot(aes(x = model, y = rmse))+
  geom_violin()
```