---
title: "Linear Model"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>
  mutate(stars = review_scores_location / 2) |>
  rename(
    borough = neighbourhood_group, 
    neighbourhood = neighbourhood
  )|>
  filter(
    borough != "State Island"
  )|>
  select(price, stars, borough, neighbourhood, room_type)|>
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )

```

fit some models
```{r}
fit = lm(price ~ stars, data = nyc_airbnb)

summary(fit)

names(summary(fit))

fit |>
   broom::tidy()|>
   select(term, estimate, p.value)
```

```{r}
fit = 
  lm(price~stars + borough, data = nyc_airbnb)

fit |>
  broom::tidy()|>
  select(term, estimate, p.value)|>
  mutate(
    term = str_replace(term,"borough", "Borough: ")
  )|>
  knitr::kable(digits = 3)
  
```


```{r}
nyc_airbnb|>
  ggplot(aes(x = stars, y = price))+
  geom_point()+
  stat_smooth(method = "lm")
```


## some diagnostics
```{r}
modelr::add_residuals(nyc_airbnb, fit)|>
  ggplot(aes(x = resid))+
           geom_histogram()
```

```{r}
modelr::add_residuals(nyc_airbnb, fit)|>
  ggplot(aes(x = borough, y = resid))+
  geom_violin()+
  ylim(-100, 100)
```

Residual against stars
```{r}
modelr::add_residuals(nyc_airbnb, fit)|>
  ggplot(aes(x = stars, y = resid))+
  geom_point()
```

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  modelr::add_predictions(fit)|>
  ggplot(aes(x = pred, y = resid))+
  geom_point()
```

Hypothesis testing
```{r}
fit |>
  broom::tidy()

fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)
```


look at both
```{r}
fit_null |>
  broom::tidy()

fit_alt |>
  broom::tidy()

anova(fit_null, fit_alt)|>
  broom::tidy()
```


```{r}
nyc_airbnb |>
  lm(price ~ stars*borough + room_type*borough, data = _) |>
  broom::tidy()
```

seperate models
```{r}
nyc_airbnb |>
  filter(borough == "Manhattan") |>
  lm(price ~ stars + room_type, data = _)|>
  broom::tidy()
```

```{r}
nyc_airbnb |>
  filter(borough == "Brooklyn") |>
  lm(price ~ stars + room_type, data = _)|>
  broom::tidy()
```

use list columns
```{r}
nyc_airbnb |>
  nest(data = -borough)|>
  mutate(
    model = map(data, \(x) lm(price ~ stars + room_type, data = x)),
    results = map(model, broom::tidy)
  )|>
  select(borough, results)|>
  unnest(results)|>
  select(borough, term, estimate) |>
  pivot_wider(
    names_from = term, 
    values_from = estimate
  )
```

## room type across manhattan neighourhood
```{r}
nyc_airbnb |>
  filter(borough == "Manhattan",
  neighbourhood == "Chinatown") |>
  lm(price ~ stars + room_type, data = _)|>
  broom::tidy()
```


```{r}
nyc_airbnb |>
  filter(borough == "Manhattan")|>
  nest(data = -(borough:neighbourhood))|>
  mutate(
    model = map(data, \(x) lm(price ~ stars + room_type, data = x)),
    results = map(model, broom::tidy)
  )|>
  select(borough, results)|>
  unnest(results)|>
  select(borough, term, estimate)|>
  pivot_wider(
    names_from = term,
    values_from = estimate
  )
```

```{r}
nyc_airbnb |>
  nest(data = -borough)|>
  mutate(
    model = map(data, \(x) lm(price ~ stars + room_type, data = x)),
    results = map(model, broom::tidy)
  )|>
  select(borough, results)|>
  unnest(results)|>
  select(borough, term, estimate)|>
  pivot_wider(
    names_from = term,
    values_from = estimate
  )
```


```{r}
nyc_airbnb |>
  filter(
    borough == "Manhattan",
    neighbourhood == "Chinatown")|>
  lm(price ~ stars + room_type, data = _)|>
  broom::tidy()
```


```{r}
nyc_airbnb |>
  filter(
    borough == "Manhattan",
    neighbourhood == "Chelsea")|>
  lm(price ~ stars + room_type, data = _)|>
  broom::tidy()
```


```{r, error=TRUE}
manhanttan_neighbourhood_fit_df = 
nyc_airbnb |>
  filter(borough == "Manhattan")|>
  nest(data = -(borough:neighbourhood))|>
  mutate(
    model = map(data, \(x) lm(price ~ stars + room_type, data = x)),
    resutls = map(model, broom::tidy)
  )|>
  select(neighbourhood, results)|>
  unnest(results)
```

```{r, error=TRUE}
manhanttan_neighbourhood_fit_df |>
  filter(str_detect(term, "room_type"))|>
  ggplot(aes(x = term, y = estimate))+
  geom_boxplot()
```

```{r, error=TRUE}
manhanttan_neighbourhood_fit_df |>
  filter(str_detect(term, "room_type"))|>
  filter(estimate >0)

nyc_airbnb |>
  filter(
    neighbourhood == "Noho",
    room_type == "Shared room"
  )

```

